"""empty message

Revision ID: 644467bebc12
Revises: 8ef8972884eb
Create Date: 2021-02-22 15:29:48.938520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644467bebc12'
down_revision = '8ef8972884eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug')
    # ### end Alembic commands ###
