"""empty message

Revision ID: 8ef8972884eb
Revises: 
Create Date: 2021-02-16 09:55:54.368592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef8972884eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_activity', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_even',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_even_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('setup_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first', sa.String(length=120), nullable=True),
    sa.Column('last', sa.String(length=120), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('investor', sa.Boolean(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('be_onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('pp_onboarding_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('break_even_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('break_even_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['break_even_id'], ['break_even.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_even_assessment_goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('break_even_assessment_id', sa.Integer(), nullable=True),
    sa.Column('risk', sa.String(length=12), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['break_even_assessment_id'], ['break_even_assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('property_code', sa.String(length=80), nullable=False),
    sa.Column('pp_action', sa.String(length=80), nullable=False),
    sa.Column('option_code', sa.String(length=80), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_facet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('break_even_assessment_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['break_even_assessment_goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('data', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['impact_id'], ['impact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_sdg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sdg', sa.String(length=80), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['impact_id'], ['impact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_property_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('product_property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_property_id'], ['product_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_property_answer')
    op.drop_table('impact_sdg')
    op.drop_table('impact_answer')
    op.drop_table('break_even_assessment_answer')
    op.drop_table('product_property')
    op.drop_table('product_facet')
    op.drop_table('impact')
    op.drop_table('break_even_assessment_goal')
    op.drop_table('break_even_answer')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('break_even_assessment')
    op.drop_table('break_even')
    op.drop_table('company')
    # ### end Alembic commands ###
